sudo: required
services:
  - docker

before_install:
  - docker build -t narcisneacsu194/docker-react -f Dockerfile.dev .

script:
  - docker run narcisneacsu194/docker-react npm run test -- --coverage
